name: ksu_integration

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: get kernel
      run: |
        mkdir kernel
        cd ./kernel

        repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-android13-5.10-2024-11

        ls -a

    
