name: ksu_integration

on:
  push:
    branches: [main]

env:
  KERNEL: "${{ github.workspace }}/kernel"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: install_packages
      run: |
        sudo apt install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo
          
    - name: get kernel
      run: |
        mkdir ./kernel && cd ./kernel

        # get kernel
        repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-android13-5.10-2024-11

        repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast

    - name: ksu_integration
      run: |
        cd "$KERNEL"

        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -

    - name: susfs
      run: |
        cd "$KERNEL"

        git clone -b gki-android13-5.10 --single-branch https://gitlab.com/simonpunk/susfs4ksu.git

        # patches
        cp ./kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch "$KERNEL/KernelSU"

        cp ./kernel_patches/50_add_susfs_in_gki-android13-5.10.patch "$KERNEL/common/"

        cp ./kernel_patches/fs/* "$KERNEL/common/fs/"

        cp ./kernel_patches/include/linux/* "$KERNEL/common/include/linux/"

        #patch
        cd "$KERNEL/KernelSU"
        patch -p1 < 10_enable_susfs_for_ksu.patch

        cd "$KERNEL/common"
        patch -p1 < 50_add_susfs_in_gki-android13-5.10.patch

    - name: build/compile
      run: |
        cd "$KERNEL"
        
        #LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh


    
